# Generated by Django 5.2.8 on 2026-01-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuser',
            name='access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='country',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
