# Generated by Django 5.2.8 on 2026-01-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_alter_spotifyuser_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
