# Generated by Django 5.2.8 on 2026-01-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('playlists', '0003_spotifyuser_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpotifyUser',
            new_name='SpotifyProfile',
        ),
    ]
